# #  Name of workflow
name: Main CI/CD

# When workflow is triggered
on:
  # Trigger on push to main
  push:
    branches: [main]

  # Trigger on PR
  pull_request:
    branches: [main]

  # Allows manual trigger
  workflow_dispatch:

# Jobs to carry out
jobs:

  deployment_prod:
    name: Deployment (Prod)
    runs-on: ubuntu-latest
    # Operating system to run job on
    if: github.ref == 'refs/heads/main'
    environment: production
     # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      # Run npm install and build on our code
      - run: npm install --legacy-peer-deps
      - run: npm run build

      # Deploy to Netlify using our production secrets
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './public'
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
